

services:
  db:
    image: postgres:15
    hostname: postgres
    ports:
        - ${POSTGRES_PORT}:5432
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - postgres_data:/var/lib/postgresql/data
    env_file:
        - .env
    restart: unless-stopped



  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  task_api:
    build: ./
    env_file: '.env'
    environment:
      POSTGRES_HOST: db
    container_name: api
    ports:
      - 9999:8000
    depends_on:
      - db

  task_broker:
    container_name: task_b
    build: ./task_client/
    depends_on:
      - task_api
    ports:
      - 9998:8002
    restart: always
    env_file:
      - ./task_client/.env


volumes:
  postgres_data:
  rabbitmq_data:

