"""auto generate migration

Revision ID: 8f9c4c5d680b
Revises: 
Create Date: 2024-12-02 00:39:12.889257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f9c4c5d680b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_name", sa.String(length=50), nullable=False),
        sa.Column("task_description", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new_task",
                "in_progress",
                "completed_successfully",
                "error",
                name="statusenum",
            ),
            server_default="new_task",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
    # ### end Alembic commands ###
